### ISSUE TITLE
Ubuntu 20.4, Ubuntu Software missing background

### ISSUE THREAD

**Issue by damned-me** [godlyranchdressing/retrowave-theme#1]
I've installed this theme yesterday on **Ubuntu 20.4**, the Ubuntu Software app **lacks background** and you only see the text and buttons. However the theme is really nice, I will use it a lot.

**Comment by godlyranchdressing** [comment]
That's really strange, I'll spin up an Ubuntu installation and see what's up. Thanks for letting me know.

@damned-me I have a fresh installation of Ubuntu up, but I'm not getting the problem. The software store just has the default theme. I'm guessing it's a snap issue. Do other themes work fine for you?

**Comment by damned-me** [comment]
Yes, all the other themes didn't bother me, I tried to reinstall it from scratch and the problem seems to have solved itself, thanks!
